--- #YAML:1.0
name:                IO-Compress-Zlib
version:             2.012
abstract:            Perl interface to zlib
license:             perl
author:              
    - Paul Marquess <pmqs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Compress::Raw::Zlib:           2.012
    IO::Compress::Base:            2.012
    IO::Uncompress::Base:          2.012
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
